###

GET http://localhost:3100/api/vaccines HTTP/1.1

###

POST http://localhost:3100/api/vaccines HTTP/1.1
Content-Type: application/json

{
    "name": "Donner",
    "description": "Vacuna buena bonita barata",
    "tecn": "nanobits",
    "date": "22-23-2021"
}


